version: "3.8"
services:
  postgres:
#   image: postgres:14.3-alpine
    image: postgres
#   restart: always  # TODO? or XXX?

    # TODO
#   volumes:
#     - ./data/postgres:/var/lib/postgresql/data

    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - '5432:5432'

  webapp:
    build: .
#   command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - '8000:8000'
    environment:
      - POSTGRES_HOST=postgres  # service name
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
    depends_on:
      - postgres
