version: "3.8"
services:
  postgres:
    image: postgres:14.3-alpine
    restart: always
    environment:
      - "POSTGRES_USER=${PGUSER}"
      - "POSTGRES_PASSWORD=${PGPASSWORD}"
      - "POSTGRES_DB=${PGDATABASE}"
    ports:
      - '5432:5432'

  webapp:
    build: .
    ports: 
      - '8000:8000'
    environment:
      - "PGHOSTADDR=${PGHOSTADDR}"
      - "PGPORT=${PGPORT}"
      - "PGUSER=${PGUSER}"
      - "PGPASSWORD=${PGPASSWORD}"
      - "PGDATABASE=${PGDATABASE}"
    links:
      - postgres
