name: Continuous Integration
on:
  push:
  schedule:
    - cron: '* 0 * * *'

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup node@16
      uses: actions/setup-node@v3
      with:
        node-version: 16
    - name: setup python@3.X
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        architecture: 'x64'
    - name: ls
      run: ls -la
    - name: setup
      run: npm run setup:ci --if-present
    - name: npm install
      run: npm ci
